import Header from './Header'
import Main from './Main'
import Footer from './Footer'
import Head from 'next/head'

export default function CookieStandAdmin() {
  
  
    return (
      <div>
        <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"/>
        <link rel="shortcut icon" href="/assets/favicon.ico" />
      </Head>
        <Header/>
        <Main/>
        <Footer/>
        
      </div>
    )
  }